'use client';

import React, { useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useGSAP } from '@gsap/react';
import { Shield, CheckCircle, Scale, Database, Cpu } from 'lucide-react';
import SpotlightCard from './SpotlightCard';

gsap.registerPlugin(useGSAP, ScrollTrigger);

const STATS = [
  {
    value: '50+',
    label: 'Evaluation Dimensions',
    sub: 'Across reasoning, faithfulness, safety, and security'
  },
  {
    value: '3×',
    label: 'Independent Expert Review',
    sub: 'Multi-specialist consensus on every critical judgment'
  },
  {
    value: '24/7',
    label: 'Adversarial Coverage',
    sub: 'Continuous red-team test suites protecting production'
  },
  {
    value: '100%',
    label: 'Trace Reproducibility',
    sub: 'Auditable traces and reviewer notes, never a black box'
  }
];

const TRUST_PILLARS = [
  {
    icon: Database,
    title: 'Reproducible Evidence',
    desc: 'Every score ships with the complete trace, reviewer notes, and reference dataset behind it — fully re-runnable under identical parameters.'
  },
  {
    icon: Scale,
    title: 'Inter-Rater Agreement',
    desc: 'Multiple verified experts judge each item; we report statistical agreement coefficients and adjudicate disagreements transparently.'
  },
  {
    icon: Shield,
    title: 'Adversarial Coverage',
    desc: 'Prompt-injection, jailbreak, and data-exfiltration suites mapped rigorously to severity bands — systematically measured, not guessed.'
  },
  {
    icon: CheckCircle,
    title: 'Severity-Graded Reporting',
    desc: 'Findings triaged by risk band and regression delta, empowering engineers to patch critical vulnerabilities before addressing minor outliers.'
  }
];

export default function TrustAndStatsSection() {
  const containerRef = useRef<HTMLDivElement>(null);
  const statsRef = useRef<(HTMLDivElement | null)[]>([]);

  useGSAP(
    () => {
      // Stagger stats reveal
      gsap.fromTo(
        statsRef.current,
        { opacity: 0, y: 30 },
        {
          opacity: 1,
          y: 0,
          stagger: 0.1,
          duration: 0.8,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: containerRef.current,
            start: 'top 80%',
            toggleActions: 'play none none reverse'
          }
        }
      );
    },
    { scope: containerRef }
  );

  return (
    <section
      id="trust"
      ref={containerRef}
      className="relative w-full bg-[#0a0a0c] text-white py-28 sm:py-36 px-6 sm:px-12 lg:px-20 border-t border-neutral-800 overflow-hidden"
    >
      <div className="max-w-6xl mx-auto relative z-10">
        {/* Header */}
        <div className="flex flex-col items-start max-w-3xl mb-16 sm:mb-20">
          <div className="flex items-center gap-2 mb-4">
            <span className="w-2 h-2 rounded-full bg-neutral-400" />
            <span className="font-mono text-xs uppercase tracking-[0.25em] text-neutral-400">
              BUILT FOR TRUST
            </span>
          </div>
          <h2 className="font-display font-semibold text-2xl sm:text-3xl md:text-5xl text-white tracking-tight leading-tight mb-5">
            Statistical Rigor, Measurable Assurance.
          </h2>
          <p className="text-neutral-400 text-sm sm:text-base md:text-lg leading-relaxed font-normal">
            Every score, recommendation, and security report generated by Evalixa is verifiable, reproducible, and defended by domain specialists.
          </p>
        </div>

        {/* 4 Key Stat Metrics */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-20">
          {STATS.map((stat, idx) => (
            <div
              key={stat.label}
              ref={(el) => {
                statsRef.current[idx] = el;
              }}
              className="p-6 sm:p-7 rounded-lg border border-neutral-800/90 bg-[#121215]/80 flex flex-col justify-between hover:border-neutral-700 transition-all duration-300 shadow-xl shadow-black/40"
            >
              <div className="font-display font-bold text-4xl sm:text-5xl text-white tracking-tight mb-3">
                {stat.value}
              </div>
              <div>
                <div className="font-display font-semibold text-sm sm:text-base text-neutral-200 mb-1">
                  {stat.label}
                </div>
                <p className="text-neutral-500 text-xs leading-relaxed font-normal">
                  {stat.sub}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* 4 Pillars Grid with SpotlightCard hover */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-8">
          {TRUST_PILLARS.map((pillar) => {
            const Icon = pillar.icon;
            return (
              <SpotlightCard
                key={pillar.title}
                spotlightColor="rgba(255, 255, 255, 0.06)"
                className="rounded-lg border border-neutral-800/90 bg-[#111114]/90 p-8 hover:border-neutral-700 transition-all duration-300"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-9 h-9 rounded-md bg-neutral-900 border border-neutral-700 flex items-center justify-center">
                    <Icon className="w-4 h-4 text-neutral-300" />
                  </div>
                  <h3 className="font-display font-semibold text-lg sm:text-xl text-white tracking-tight">
                    {pillar.title}
                  </h3>
                </div>
                <p className="text-neutral-400 text-xs sm:text-sm md:text-[15px] leading-relaxed font-normal">
                  {pillar.desc}
                </p>
              </SpotlightCard>
            );
          })}
        </div>
      </div>
    </section>
  );
}
